### ISSUE TITLE
Configurer le symfonycasts_reset_password

### ISSUE THREAD

**Issue by Shurtugl** [Shurtugl/BestQodeurPeriod#12]
@caliendojulien 

Pour faire court : Peux-tu m'indiquer le contenu d'un fichier XML stp ?

Nous avons un système d'authentification qui gère le 'reset password'. Cela a été créé par Quentin dans la branche QSSecurity. Le concept fonctionne sur son ordinateur ENI. Je soupçonne un fichier manquant dans le commit pour bien configurer ...

J'ai un problème lors de 'composer install'. La console me répond ceci lors du cache:clear  (error code 1)
>>The child config "request_password_repository" under "symfonycasts_reset_password" must be configured: A class that implements ResetPasswordRequestRepositoryInterface - usually your ResetPasswordRequestRepository.

J'ai recherché, il me faut informer le fichier 
>>reset_password_services.xml 

Qui se trouve dans 
>>/vendor/symfonycasts/reset-password-bundle/src/Resources/config 

Pour l'instant il contient le code cf ci-joint [au format .xml.txt car github refuse le .xml] mais je suppose que le repository  
>>ResetPasswordRequestRepository.php 

(qui existe déjà dans la branche et a été pull sans problème) doit être renseigné.  
J'ai tenté de créer un make:entity de User, un make:auth suivi d'un make:reset-password dans un autre projet, pour voir où et comment cette info était renseignée, mais j'ai fait choux blanc.
J'ai aussi tenté de lancer la commande avec --no-scripts et j'ai alors accès à la console , mais même en faisant cela suivi d'un make:reset-password le problème persiste lorsque je serve sur 127.0.0.1 

Merci de ton aide.

Voici mes recherches : 

https://github.com/SymfonyCasts/reset-password-bundle/issues/46
https://github.com/SymfonyCasts/reset-password-bundle/pull/48
\vendor\symfonycasts\reset-password-bundle\docs\manual-setup.md
\vendor\symfonycasts\reset-password-bundle\src\DependencyInjection\SymfonyCastsResetPasswordExtension.php 
[ligne 27 notamment ]
Le xml en question : 
[reset_password_services.xml.txt](https://github.com/Shurtugl/BestQodeurPeriod/files/10774000/reset_password_services.xml.txt)

**Comment by caliendojulien** [comment]
@Shurtugl @QSwiderski 

Je pense savoir d'ou vient le problème.
L'équipe du reset-password-bundle a empéché l'installation lorsque php est entre les versions 8.1.0 et 8.1.10.
Tu peux le voir ici : https://github.com/SymfonyCasts/reset-password-bundle/releases/tag/v1.15.0

Du coup, tu n'a que deux solutions : 

- Augmenter ta version de php
- Aller modifier, a la main, dans le fichier composer.json, la version du reset-password-bundle pour lui donner une version précédente.

Je pense que le plus simple c'est de monter ta version de php.

**Comment by Shurtugl** [comment]
@caliendojulien 
J'ai
-mis à jour mon PHP et la ligne addhoc dans le composer.json
-corrigé un souci de mon php.ini (il manquait extension=php_zip.dll )
-supprimé les packages dans le vendor

A chaque étape relancé un composer install
->toujours le même problème.

En attendant il y a de quoi faire sur la branche PA_location et (espère) solutionner lundi = tu as le droit de ne pas m'aider un dimanche tout de même

**Comment by caliendojulien** [comment]
Le groupe AnneSo Bruno Deana a eu le même souci et a réussi a trouver la solution. On voit ça avec eux lundi.
